### ISSUE TITLE
Multi elements in contains function

### ISSUE THREAD

**Issue by gurkerl83** [blazejkustra/dynamode#10]
Just a quick question, the contains function or the condition API seems limited allowing only a single entry in the array, is there room for improvement or is this final?
Thx!

**Comment by blazejkustra** [comment]
Hi! This is a limitation of DynamoDB. The contains function in Amazon DynamoDB is indeed designed to only search for a single value within a set or a list attribute. The contains function essentially verifies if a specific attribute contains a certain value. 

Thus Dynamode API aligns with this limitation. Maybe [this](https://stackoverflow.com/a/44997988) helps.
