### ISSUE TITLE
[BUG] cannot install this package by pnpm

### ISSUE THREAD

**Issue by moonrailgun** [blazejkustra/dynamode#12]
### Summary:

Follow document to install this package with pnpm and occur below problem

![image](https://github.com/blazejkustra/dynamode/assets/6964737/996fdf6b-fecf-4a1c-86a0-cc723f584ee5)

its looks like be block with `package.json`.

because document allow install with pnpm, so i think this should be a bug
![image](https://github.com/blazejkustra/dynamode/assets/6964737/a6b99ae3-7c2b-438d-95b8-537eb7d95059)

### Environment:

Operating System & version: windows 10
Node.js version (`node -v`): v18.18.0
NPM version: (`npm -v`): pnpm version is 8.3.1
Dynamode version: 0.7.3

### Other:
- [x] I have read through the Dynamode documentation before posting this issue
- [x] I have searched through the GitHub issues (including closed issues) and pull requests to ensure this issue has not already been raised before
- [x] I have searched the internet to ensure this issue hasn't been raised or answered before

**Comment by blazejkustra** [comment]
Interesting! Thanks for posting this issue I'll look into it tomorrow 😄

**Comment by blazejkustra** [comment]
@moonrailgun It should be fine now, with version 0.7.5. I also updated the docs:
![image](https://github.com/blazejkustra/dynamode/assets/46095609/5d29cfce-0dfc-4296-99ad-761ced2a88f7)
