### ISSUE TITLE
When array of .in([]) is empty

### ISSUE THREAD

**Issue by gurkerl83** [blazejkustra/dynamode#16]
Hi,

we receive the following error when the the array we put here ```.in([])``` is empty.

```
const experimentIdsWeAreInterestedIn = []; // determined in a previous operation
SomeEntityManager.condition().attribute('experimentId').in(experimentIdsWeAreInterestedIn)
```

```
Error: Invalid FilterExpression: Syntax error; token: ")", near: "()"
```

Maybe a check if the argument is of type array and it is is of length > 0 can be added in the condition API here?

````
 in: (values: Array<EntityValue<E, K>>): C => {
   const processedValues = values.map((value) => transformValue(this.entity, key, value));
   this.operators.push(...OPERATORS.in(key, processedValues));
   return this;
},
```

I think this is should be checked at library level and not in user space.

Thx!

**Comment by blazejkustra** [comment]
Taking a look now, in the meantime - any feedback regarding dynamode, do you like it? 😄

**Comment by gurkerl83** [comment]
We really love it; it's super simple to use and much more elegant than what was previously in the code base. The syntax of the original DynamoDB library is really ugly; they should hire you to fix that. To be honest, we're using it as an interim solution before migrating to MongoDB. Often, wrong decisions about the database model are made at the start of a project. We've looked around for ways to fix this problem in a clean yet quick manner. One thing was clear: we did not want to integrate too deeply into other existing DynamoDB libraries, and DynamoMode seems a perfect fit for that.

Thanks!

**Comment by blazejkustra** [comment]
Should be fixed with version `0.7.7`. Let me knows if that fixes your problem!

**Comment by gurkerl83** [comment]
Hi again,

right now, it seems passing an empty array skips the query and **gives us everything** because we pass the condition in here

```
const experimentIdsWeAreInterestedIn = []; // determined in a previous operation
SomeEntityManager.condition().attribute('experimentId').in(experimentIdsWeAreInterestedIn)
await SomeEntityManager.scan().condition(laboratoryCondition).run();
```

In JS the equivalent what we want to achieve is here

```
const array = ['a', 'b', 'c'];
const filterValues = []; // empty array

const filteredArray = array.filter(element => filterValues.includes(element));
console.log(filteredArray); // This will log []
```
Maybe the something more underneath triggers the error from before, still passing even an empty array.

```
Error: Invalid FilterExpression: Syntax error; token: ")", near: "()"
```

Thx!

**Comment by blazejkustra** [comment]
I agree with you, should be fixed with https://github.com/blazejkustra/dynamode/pull/19

**Comment by gurkerl83** [comment]
Perfect, thx so much, i will try tomorrow and provide feedback!
