### ISSUE TITLE
When array of .batchGet([]) is empty

### ISSUE THREAD

**Issue by gurkerl83** [blazejkustra/dynamode#18]
Hi, sry to bring another issue up.

We currently utilize the batchGet method for retrieving multiple items in a single operation. This method functions effectively when the input array contains at least one element. However, we encounter issues when the array is empty, leading to operational failures.

To enhance the process, it would be beneficial to implement a check that verifies the presence of at least one element in the array before executing the batchGet operation. If the array is empty, the operation could be bypassed, allowing us to use a predefined default for the items.

Our implementation is as follows:

The `partition-key` we use in these operations is `id`

For a **successful** operation:
```
const experimentIdsWeAreInterestedIn = [ { id: 'abc' }, { id: 'def' } ]; // determined in a previous step
const { items: experimentItems = [] } = await SomeEntityManager.batchGet(experimentIdsWeAreInterestedIn);
```

For an **unsuccessful** operation due to an empty array:
```
const experimentIdsWeAreInterestedIn = []; // determined in a previous step
const { items: experimentItems = [] } = await SomeEntityManager.batchGet(experimentIdsWeAreInterestedIn);
```

It's worth considering if this array length check could be applied to other batch operations as well. A **critical aspect** of this enhancement is **ensuring the returned object maintains the correct structure / object with items in it**, possibly assigning a default value, like null, when the operation is skipped.

**Comment by blazejkustra** [comment]
No problem, thanks for making this package more usable overall! 0.7.8 is published now 😄

**Comment by gurkerl83** [comment]
Nice!

**Comment by blazejkustra** [comment]
> A critical aspect of this enhancement is ensuring the returned object maintains the correct structure / object with items in it, possibly assigning a default value, like null, when the operation is skipped.

Empty input === empty output for all batch methods. Let me know if that makes sense
