### ISSUE TITLE
This is not a bug but rather a question about update vs put

### ISSUE THREAD

**Issue by gurkerl83** [blazejkustra/dynamode#22]
Executing a update operation it seems knowing which field to update is the way to go right e.g.

```ts
// Appends a single collaborator to the existing list of collaborators
export async function addCollaborator(experimentId: string, collaboratorId: string) {
  // Prepare update properties to append a collaborator to the list
  const updateProps = {
    listAppend: {
      collaborators: [collaboratorId],
    },
  };

  // Perform the update operation
  await ExperimentEntityManager.update({ id: experimentId }, updateProps);
}
```

On the other hand we have situations where it is unclear what fields to update, one or more, maybe values are undefined.

```ts
export const updateExperiment = async (experiment: Experiment) => {
  console.log('updateExperiment', experiment);
  try {
    const updatedExperiment = await ExperimentEntityManager.put(experiment as ExperimentEntity);
    return updatedExperiment;
  } catch (err) {
    const dbError = new DatabaseError('Experiment', 'update', experiment.id, { error: err as Error });
    console.log(dbError);
    throw dbError;
  }
};
```

Is my understanding correct that we can leverage the put operation then? Digging a bit the code I found the behavior of put uses the following helper. 

For reference see the option for marshal `removeUndefinedValues: true` https://github.com/blazejkustra/dynamode/blob/08d4ae449ae74e038f7e6cd9e8e4555f556ddbba/lib/utils/converter.ts#L5

For explanation see https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/Package/-aws-sdk-util-dynamodb/Interface/marshallOptions/

Thx!

**Comment by blazejkustra** [comment]
Hi! Under the hood these methods fire different dynamodb commands:
- `update` uses [UpdateItem API](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_UpdateItem.html)
- `put` uses [PutItem API](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_PutItem.html)

Above are fundamentally different but yes, both should get the job done if you want to update a certain item 


First of all I think you shouldn't use assertion (`as ExperimentEntity`) in your code, instead provide a valid type for the experiment argument
```ts
export const updateExperiment = async (experiment: ExperimentEntity) => {
  console.log('updateExperiment', experiment);
  try {
    const updatedExperiment = await ExperimentEntityManager.put(experiment);
    return updatedExperiment;
  } catch (err) {
    const dbError = new DatabaseError('Experiment', 'update', experiment.id, { error: err as Error });
    console.log(dbError);
    throw dbError;
  }
};
```

And call this function like this:
```ts
updateExperiment(new ExperimentEntity({...experimentValues}))
```

**Comment by blazejkustra** [comment]
You have to know that updating an item with `EntityManager.put` might be a bad idea if you are updating experiments frequently as this may lead to some race condition and you may lose data.


Let's say you have a function that updates this experiment and pushes new collaborators to it, and there are two updates running at the same time:

initial data:
```
Experiment: {id: 1, collaborators: ["0"] }
```

Running threads:
```
THREAD1: Experiment.get()
THREAD2: Experiment.get()
THREAD1: Experiment.put(new ExperimentEntity({ ...initialData, collaborators: [...initialData, "1"] }))
THREAD2: Experiment.put(new ExperimentEntity({ ...initialData, collaborators: [...initialData, "2"] }))
```

The item will end up as:
```
Experiment: {id: 1, collaborators: ["0", "2"] }
```

While the correct value should be:
```
Experiment: {id: 1, collaborators: ["0", "1", "2"] }
```

With update there is no such problem as you don't need to fetch the item first

**Comment by blazejkustra** [comment]
You can update fields dynamically with `update`, I did this in one of my project:
```ts
if (status !== oldStatus) {
  await ListManager.update(List.getPrimaryKey(listId), {
    increment: {
      [`progress.${status}`]: 1,
    },
    decrement: {
      [`progress.${oldStatus}`]: 1,
    },
  });
}
```

Where List is defined as follows:
```ts
type ListStatus = 'active' | 'deleted';

type ListProgress = {
  unchecked: number;
  checked: number;
  unavailable: number;
};

type ListProps = UserTableProps & {
  name: string;
  status: ListStatus;
  ownerUsername: string;
  progress: ListProgress;
};

export default class List extends UserTable {
  @attribute.string()
  listId: string;

  @attribute.string()
  name: string;

  @attribute.string()
  ownerUsername: string;

  @attribute.object()
  progress: ListProgress;

  @attribute.string()
  status: ListStatus;

  constructor(props: ListProps) {
    super(props);

    this.listId = props.pk;
    this.name = props.name;
    this.ownerUsername = props.ownerUsername;
    this.status = props.status;
    this.progress = props.progress;
  }

  static getPrimaryKey(listId: string): UserTablePrimaryKey {
    return {
      pk: listId,
      sk: List.name,
    };
  }
}
```

**Comment by blazejkustra** [comment]
@gurkerl83 I hope this helps!

**Comment by gurkerl83** [comment]
Hi thx for the quick response, for now we want to keep it really simple, so although `put` is not recommended updating frequently, we could use it when the object to update has potential undefined values on it right? The marshal option used in a helper of the put operation `removeUndefinedValues: true` will create a new object / expression without the keys which are currently undefined right?

**Comment by gurkerl83** [comment]
@blazejkustra This is a stack trace of a collaborator. The code is using the `put` operation, there are undefined values but this should be handled. I do not really understand the stack trace in full, but it seems rather a problem with the empty array in it.

![MicrosoftTeams-image](https://github.com/blazejkustra/dynamode/assets/301689/d668cbfc-be9c-4edb-8216-f45dc13d211a)

**Comment by blazejkustra** [comment]
Can you post a minimal code to reproduce it? Model and the way you call put method should be enough, thanks!

**Comment by blazejkustra** [comment]
I can reproduce this using this code ([model code](https://github.com/blazejkustra/dynamode/blob/1d7c8ef5ed2528e3fe8c01e18cf4af14559e80b0/examples/User/model.ts)):
```ts
  const userUpdate = await UserManager.update(
    { partitionKey: 'pk1', sortKey: 'sk1' },
    {
      set: {
        age: undefined,
      },
      add: {},
    },
  );
```

Most likely he used update method instead of put:
![image](https://github.com/blazejkustra/dynamode/assets/46095609/4b9dd1f5-07b5-4f50-aef9-36a03112be8b)
