### ISSUE TITLE
[BUG] startAt fails when querying secondary indices

### ISSUE THREAD

**Issue by quinnromanek** [blazejkustra/dynamode#23]
### Summary:

The docs provide the example of `startAt`:
```
const response1 = await UserManager.query().partitionKey('partitionKey').eq('1').run(); 
const response2 = await UserManager.query().partitionKey('partitionKey').eq('1').startAt(response1.lastKey).run();
```

However, if `partitionKey` is not a the primary partition key of the table, this fails.  This is because `convertPrimaryKeyToAttributeValues` is used to convert `LastEvaluatedKey` from the dynamo format to a TS object, but it only populates the primary partitionKey and sortKey of the table, not the global secondary index that you are querying. This results in a Dynamo error:
```
ValidationException: Exclusive Start Key must have same size as table's key schema
```
since Dynamo is expecting the primary partition + sort pair AND the secondary index partition + sort pair in the `ExclusiveStartKey` field. 

### Other:
- [X ] I have read through the Dynamode documentation before posting this issue
- [X] I have searched through the GitHub issues (including closed issues) and pull requests to ensure this issue has not already been raised before
- [X] I have searched the internet to ensure this issue hasn't been raised or answered before

**Comment by blazejkustra** [comment]
Thanks for finding this @quinnromanek, I'll post a PR this week.

**Comment by blazejkustra** [comment]
A fix is up in the PR above, I still need to add some new tests to ensure everything else works well 😄 

Meanwhile try installing [1.0.1-rc.0](https://www.npmjs.com/package/dynamode/v/1.0.1-rc.0) and let me know if it works well for you.

**Comment by blazejkustra** [comment]
@quinnromanek Let me know if it works well for you now 😄
