### ISSUE TITLE
Unable to pass in undefined attributes intended to be optional

### ISSUE THREAD

**Issue by atypicalflame** [blazejkustra/dynamode#34]
Hi,
I have a table model that has an attribute defined as String | undefined. If undefined, that attribute shouldn't be written into the object. However, I'm getting an error `Error: Pass options.removeUndefinedValues=true to remove undefined values from map/array/set.` Am i missing something?
`

**Comment by blazejkustra** [comment]
It'll be hard to help without any code provided, please share the minimal reproduction steps (model and the code that breaks)
